name: score-eg-thumbnail-service
services:
    rabbitmq-WfmJxZ:
        environment:
            RABBITMQ_DEFAULT_PASS: guest
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_ERLANG_COOKIE: fnJcESBJzlfzhroOKWkq
        healthcheck:
            test:
                - CMD-SHELL
                - rabbitmq-diagnostics -q check_port_connectivity
            timeout: 5s
            interval: 2s
            retries: 5
        image: rabbitmq:3-management-alpine
        ports:
            - target: 5672
              published: "15672"
            - target: 15672
              published: "16672"
        restart: always
        volumes:
            - type: volume
              source: rabbitmq-WfmJxZ-data
              target: /var/lib/rabbitmq
    rabbitmq-WfmJxZ-init:
        command:
            - -c
            - |
              set -exu
              for s in /db-scripts/*.sh; do source $$s; done
        depends_on:
            rabbitmq-WfmJxZ:
                condition: service_healthy
                restart: true
                required: false
        entrypoint:
            - /bin/sh
        environment:
            RABBITMQ_ERLANG_COOKIE: fnJcESBJzlfzhroOKWkq
        image: rabbitmq:3-management-alpine
        labels:
            dev.score.compose.labels.is-init-container: "true"
        network_mode: service:rabbitmq-WfmJxZ
        volumes:
            - type: bind
              source: .score-compose/mounts/rabbitmq-WfmJxZ-db-scripts
              target: /db-scripts
    thumbnail-service-main:
        annotations:
            compose.score.dev/workload-name: thumbnail-service
        build:
            context: .
        depends_on:
            wait-for-resources:
                condition: service_started
                required: false
        environment:
            AMQP_CONNECTION: amqp://user-sAPXrduB:samPPpygmFFFreTa@rabbitmq-WfmJxZ:5672/vhost-uBuflISS
            AMQP_THUMBNAILING_ROUTING_KEY: thumbnail-generation
        hostname: thumbnail-service
    wait-for-resources:
        command:
            - echo
        depends_on:
            rabbitmq-WfmJxZ:
                condition: service_healthy
                required: true
            rabbitmq-WfmJxZ-init:
                condition: service_completed_successfully
                required: true
        image: alpine
volumes:
    rabbitmq-WfmJxZ-data:
        driver: local
